# File names are either absolute or relative to the parent folder of the vhdl_ls.toml file
[libraries]
icescint.files = [
  'src/**/*.vhd',
  'ip/**/*.vhd',
  'lib/**/*.vhd',
]
#XilinxCoreLib.files = [
#  '/opt/Xilinx/14.7/ISE_DS/ISE/vhdl/src/XilinxCoreLib/**/*.vhd',
#]
#unisim.files = [
#    '/opt/Xilinx/14.7/ISE_DS/ISE/vhdl/src/unisims/**/*.vhd'
#]
vunit_lib.files = [
  '/usr/lib/python3.9/site-packages/vunit/vhdl/**/*.vhd'
]
